# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/el-rafa/CLionProjects/Rythin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/el-rafa/CLionProjects/Rythin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/el-rafa/CLionProjects/Rythin/CMakeFiles /home/el-rafa/CLionProjects/Rythin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/el-rafa/CLionProjects/Rythin/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/el-rafa/CLionProjects/Rythin/CMakeFiles /home/el-rafa/CLionProjects/Rythin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/el-rafa/CLionProjects/Rythin/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rythin

# Build rule for target.
rythin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rythin
.PHONY : rythin

# fast build rule for target.
rythin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/build
.PHONY : rythin/fast

log_errors.o: log_errors.cpp.o
.PHONY : log_errors.o

# target to build an object file
log_errors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/log_errors.cpp.o
.PHONY : log_errors.cpp.o

log_errors.i: log_errors.cpp.i
.PHONY : log_errors.i

# target to preprocess a source file
log_errors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/log_errors.cpp.i
.PHONY : log_errors.cpp.i

log_errors.s: log_errors.cpp.s
.PHONY : log_errors.s

# target to generate assembly for a file
log_errors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/log_errors.cpp.s
.PHONY : log_errors.cpp.s

r_inter.o: r_inter.cpp.o
.PHONY : r_inter.o

# target to build an object file
r_inter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_inter.cpp.o
.PHONY : r_inter.cpp.o

r_inter.i: r_inter.cpp.i
.PHONY : r_inter.i

# target to preprocess a source file
r_inter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_inter.cpp.i
.PHONY : r_inter.cpp.i

r_inter.s: r_inter.cpp.s
.PHONY : r_inter.s

# target to generate assembly for a file
r_inter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_inter.cpp.s
.PHONY : r_inter.cpp.s

r_lex.o: r_lex.cpp.o
.PHONY : r_lex.o

# target to build an object file
r_lex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_lex.cpp.o
.PHONY : r_lex.cpp.o

r_lex.i: r_lex.cpp.i
.PHONY : r_lex.i

# target to preprocess a source file
r_lex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_lex.cpp.i
.PHONY : r_lex.cpp.i

r_lex.s: r_lex.cpp.s
.PHONY : r_lex.s

# target to generate assembly for a file
r_lex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_lex.cpp.s
.PHONY : r_lex.cpp.s

r_parser.o: r_parser.cpp.o
.PHONY : r_parser.o

# target to build an object file
r_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_parser.cpp.o
.PHONY : r_parser.cpp.o

r_parser.i: r_parser.cpp.i
.PHONY : r_parser.i

# target to preprocess a source file
r_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_parser.cpp.i
.PHONY : r_parser.cpp.i

r_parser.s: r_parser.cpp.s
.PHONY : r_parser.s

# target to generate assembly for a file
r_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/r_parser.cpp.s
.PHONY : r_parser.cpp.s

rhythin.o: rhythin.cpp.o
.PHONY : rhythin.o

# target to build an object file
rhythin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/rhythin.cpp.o
.PHONY : rhythin.cpp.o

rhythin.i: rhythin.cpp.i
.PHONY : rhythin.i

# target to preprocess a source file
rhythin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/rhythin.cpp.i
.PHONY : rhythin.cpp.i

rhythin.s: rhythin.cpp.s
.PHONY : rhythin.s

# target to generate assembly for a file
rhythin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/rhythin.cpp.s
.PHONY : rhythin.cpp.s

t_tokens.o: t_tokens.cpp.o
.PHONY : t_tokens.o

# target to build an object file
t_tokens.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/t_tokens.cpp.o
.PHONY : t_tokens.cpp.o

t_tokens.i: t_tokens.cpp.i
.PHONY : t_tokens.i

# target to preprocess a source file
t_tokens.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/t_tokens.cpp.i
.PHONY : t_tokens.cpp.i

t_tokens.s: t_tokens.cpp.s
.PHONY : t_tokens.s

# target to generate assembly for a file
t_tokens.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rythin.dir/build.make CMakeFiles/rythin.dir/t_tokens.cpp.s
.PHONY : t_tokens.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rythin"
	@echo "... log_errors.o"
	@echo "... log_errors.i"
	@echo "... log_errors.s"
	@echo "... r_inter.o"
	@echo "... r_inter.i"
	@echo "... r_inter.s"
	@echo "... r_lex.o"
	@echo "... r_lex.i"
	@echo "... r_lex.s"
	@echo "... r_parser.o"
	@echo "... r_parser.i"
	@echo "... r_parser.s"
	@echo "... rhythin.o"
	@echo "... rhythin.i"
	@echo "... rhythin.s"
	@echo "... t_tokens.o"
	@echo "... t_tokens.i"
	@echo "... t_tokens.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

