# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/el-rafa/VSCode/Rhythin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/el-rafa/VSCode/Rhythin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/el-rafa/VSCode/Rhythin/CMakeFiles /home/el-rafa/VSCode/Rhythin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/el-rafa/VSCode/Rhythin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rhythin

# Build rule for target.
rhythin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rhythin
.PHONY : rhythin

# fast build rule for target.
rhythin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/build
.PHONY : rhythin/fast

src/log_errors.o: src/log_errors.cc.o
.PHONY : src/log_errors.o

# target to build an object file
src/log_errors.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/log_errors.cc.o
.PHONY : src/log_errors.cc.o

src/log_errors.i: src/log_errors.cc.i
.PHONY : src/log_errors.i

# target to preprocess a source file
src/log_errors.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/log_errors.cc.i
.PHONY : src/log_errors.cc.i

src/log_errors.s: src/log_errors.cc.s
.PHONY : src/log_errors.s

# target to generate assembly for a file
src/log_errors.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/log_errors.cc.s
.PHONY : src/log_errors.cc.s

src/r_inter.o: src/r_inter.cc.o
.PHONY : src/r_inter.o

# target to build an object file
src/r_inter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_inter.cc.o
.PHONY : src/r_inter.cc.o

src/r_inter.i: src/r_inter.cc.i
.PHONY : src/r_inter.i

# target to preprocess a source file
src/r_inter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_inter.cc.i
.PHONY : src/r_inter.cc.i

src/r_inter.s: src/r_inter.cc.s
.PHONY : src/r_inter.s

# target to generate assembly for a file
src/r_inter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_inter.cc.s
.PHONY : src/r_inter.cc.s

src/r_lex.o: src/r_lex.cc.o
.PHONY : src/r_lex.o

# target to build an object file
src/r_lex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_lex.cc.o
.PHONY : src/r_lex.cc.o

src/r_lex.i: src/r_lex.cc.i
.PHONY : src/r_lex.i

# target to preprocess a source file
src/r_lex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_lex.cc.i
.PHONY : src/r_lex.cc.i

src/r_lex.s: src/r_lex.cc.s
.PHONY : src/r_lex.s

# target to generate assembly for a file
src/r_lex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_lex.cc.s
.PHONY : src/r_lex.cc.s

src/r_parser.o: src/r_parser.cc.o
.PHONY : src/r_parser.o

# target to build an object file
src/r_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_parser.cc.o
.PHONY : src/r_parser.cc.o

src/r_parser.i: src/r_parser.cc.i
.PHONY : src/r_parser.i

# target to preprocess a source file
src/r_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_parser.cc.i
.PHONY : src/r_parser.cc.i

src/r_parser.s: src/r_parser.cc.s
.PHONY : src/r_parser.s

# target to generate assembly for a file
src/r_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/r_parser.cc.s
.PHONY : src/r_parser.cc.s

src/rhythin.o: src/rhythin.cc.o
.PHONY : src/rhythin.o

# target to build an object file
src/rhythin.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/rhythin.cc.o
.PHONY : src/rhythin.cc.o

src/rhythin.i: src/rhythin.cc.i
.PHONY : src/rhythin.i

# target to preprocess a source file
src/rhythin.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/rhythin.cc.i
.PHONY : src/rhythin.cc.i

src/rhythin.s: src/rhythin.cc.s
.PHONY : src/rhythin.s

# target to generate assembly for a file
src/rhythin.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/rhythin.cc.s
.PHONY : src/rhythin.cc.s

src/t_tokens.o: src/t_tokens.cc.o
.PHONY : src/t_tokens.o

# target to build an object file
src/t_tokens.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/t_tokens.cc.o
.PHONY : src/t_tokens.cc.o

src/t_tokens.i: src/t_tokens.cc.i
.PHONY : src/t_tokens.i

# target to preprocess a source file
src/t_tokens.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/t_tokens.cc.i
.PHONY : src/t_tokens.cc.i

src/t_tokens.s: src/t_tokens.cc.s
.PHONY : src/t_tokens.s

# target to generate assembly for a file
src/t_tokens.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rhythin.dir/build.make CMakeFiles/rhythin.dir/src/t_tokens.cc.s
.PHONY : src/t_tokens.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rhythin"
	@echo "... src/log_errors.o"
	@echo "... src/log_errors.i"
	@echo "... src/log_errors.s"
	@echo "... src/r_inter.o"
	@echo "... src/r_inter.i"
	@echo "... src/r_inter.s"
	@echo "... src/r_lex.o"
	@echo "... src/r_lex.i"
	@echo "... src/r_lex.s"
	@echo "... src/r_parser.o"
	@echo "... src/r_parser.i"
	@echo "... src/r_parser.s"
	@echo "... src/rhythin.o"
	@echo "... src/rhythin.i"
	@echo "... src/rhythin.s"
	@echo "... src/t_tokens.o"
	@echo "... src/t_tokens.i"
	@echo "... src/t_tokens.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

